### ISSUE TITLE
Improve UI/UX Z-Index CSS

### ISSUE THREAD

**Issue by islandbitcoin** [islandbitcoin/nostr-chat-widget#1]
Three main UI improvements need to be completed:

1. On Firefox and Chrome, the widget is underneath images and flex boxes on the website. The widget needs to be always on top of everything else on the webpage. 
2. The color scheme and text formatting should not be inherited from any css classes that come from the main.css.
3. The overall size of the icons, buttons and text seems to be larger than normal size, needs to be more standardized to other chat box templates out there in the wild. 

an approved PR with these changes completed will fulfill [the bounty](https://nostrbounties.com/b/naddr1qq9rzd3cx5mrxvfexccsygqqqqqqq7a0wdm4a2m7a5lfn8gr9engmquc8qhh05ct28lu07g4sgpsgqqqw4rs50yf7p) on nostrbounties.com

**Comment by npub1zenn0** [comment]
> the widget is underneath images and flex boxes on the website.

Is this referring to the https://nostri.chat/ website or something else? Because it doesn't appear to be underneath anything for me, even though it has no z-index.

> an approved PR 

On this fork or pablof7z's?

**Comment by islandbitcoin** [comment]
yea, this is nostri.chat. here is a screenshot of my site when I add it:
![Screenshot 2023-06-14 at 7 59 26 PM](https://github.com/islandbitcoin/nostr-chat-widget/assets/34528298/8caf7d16-c12a-42bb-95ea-23c460bfb7f1)

the PR should be on this fork.

**Comment by f90fwT** [comment]
Hey @islandbitcoin i made a version with a few improvements regarding UI including the improvements you wanted and more like full mobile support. 
This is the repo: [f90fwT/nostr-chat-widget](https://github.com/f90fwT/nostr-chat-widget)
 and i have setup a [hosted version so you can test it](https://nostri-chat-hosted.f9ofwt.click/demo) you can also use that version to test it with your own site.
Let me know if you have any improvements or if i should make a PR, thank you!

**Comment by f90fwT** [comment]
I now finished implemented everything! Let me know if you have any aesthetic prefererces

**Comment by f90fwT** [comment]
@islandbitcoin Should i make the PR, or does it not meet your requirements? Let me know

**Comment by islandbitcoin** [comment]
nice! I'll check it out this evening 👍

**Comment by f90fwT** [comment]
👍 Okay, thank you!

**Comment by f90fwT** [comment]
@islandbitcoin If its ok i can make the PR, and if you want i can also do #2

**Comment by islandbitcoin** [comment]
@f90fwT 
Love how it looks in the demo, definitely fulfills my requirement. 
looks great on my website! 

make a PR and DM me a lightning address (or I can zap you).

once I approve the PR I'll make the payment.

and yes, you can start on https://github.com/islandbitcoin/nostr-chat-widget/issues/2

**Comment by f90fwT** [comment]
Ok, thank you @islandbitcoin! You can use the lightning address on my [nostr](nostr://npub1z8gdrdvdvd5y3ex3np3ewrfklf44da0pes8nwmafhgzfafv3yhhq5rju0y) profile (a zap is ok), or the bitcoin address on my [website](https://f9OfwT.click/contact).

I will share some ideas on #2 after i make a concept

**Comment by f90fwT** [comment]
@islandbitcoin PR is made with #3 !
