### ISSUE TITLE
Create multiple admin settings

### ISSUE THREAD

**Issue by islandbitcoin** [islandbitcoin/nostr-chat-widget#2]
Two settings improvements need to be completed:

1. Create admin settings or config file that automatically logs in the widget to anonymous (ephemeral keys). Give the user the option to change from Anonymous to NIP-07 or NIP-46 at any time on the webpage.
2. Create admin settings to change the color scheme.

Stretch Goal (additional 500k sats):
- Implement [NIP-28](https://github.com/nostr-protocol/nips/blob/master/28.md) support on this widget, giving the nostri.chat admin full moderation to a public chat.

an approved PR with these changes completed will fulfill [the bounty](https://nostrbounties.com/b/naddr1qq9rzd3cx5mrxv3exvuqygqqqqqqq7a0wdm4a2m7a5lfn8gr9engmquc8qhh05ct28lu07g4sgpsgqqqw4rs20r3ds) on nostrbounties.com

**Comment by Dhruv245** [comment]
HI, would love to apply for this. Let me know when to start

**Comment by islandbitcoin** [comment]
> HI, would love to apply for this. Let me know when to start

go for it 👍

**Comment by f90fwT** [comment]
@islandbitcoin What do you think of this flow for authenticating as Anonymous by default?

https://github.com/islandbitcoin/nostr-chat-widget/assets/137908879/5b038f3e-5d9d-48e4-987a-9e32958bd741

**Comment by f90fwT** [comment]
I was also thinking of something like this for easier configuring of the widget. 

https://github.com/islandbitcoin/nostr-chat-widget/assets/137908879/2f36c211-6a9f-4293-aeef-8899e0742dd5

**Comment by f90fwT** [comment]
@islandbitcoin I implemented all the basic things you asked for!

https://github.com/islandbitcoin/nostr-chat-widget/assets/137908879/092650e0-3ba1-44d3-84ef-9bd170509ed5

Let me know if something like this is good enough, or things you whould like to see change. I also send you a DM on nostr about your integrating with your site. I still need to do some code cleaning up ect, before making the commit/PR

**Comment by islandbitcoin** [comment]
This looks good! I don't see anything I would change. 👍 

I don't see a nostr DM - hopefully you sent it to the correct npub!
@npub1qqqqqqrm4aehwh4t0mknaxvaqvhxdrvrnquz7a7npdgll3lezkpqq3j5a5

**Comment by f90fwT** [comment]
Hmm that's wierd... Can confirm i sent it to the correct npub.. And i can see it on multiple clients. Do you have some other way to private message @islandbitcoin ?

**Comment by islandbitcoin** [comment]
hit me on my other nostr, I use Damus with this one: @npub1qqqqqq0u2gj96tdfvqymdqn739k4s0h9rzdwyegfmalv28j7a5ssh5ntu2

**Comment by f90fwT** [comment]
@islandbitcoin PR is created with #4

**Comment by f90fwT** [comment]
Hosted version is also updated with https://nostri-chat-hosted.f9ofwt.click/

**Comment by islandbitcoin** [comment]
I made a comment on the PR
